name: GenAI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  genai-review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install openai==0.28

    - name: Create diff file
      run: |
        git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
        git diff origin/${{ github.base_ref }}...HEAD > diff.txt
        head -n 20 diff.txt || true

    - name: Run GenAI Review
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python ai_review.py diff.txt

